### ISSUE TITLE
Unable to download the data set (connection timed out)

### ISSUE THREAD

**Issue by krshrimali** [STAIR-Lab-CIT/STAIR-actions#11]
Hi, thanks for your great work!

I'm unable to download the dataset, connection times out (tried from multiple locations). Could you please take a look?

Thanks!

**Comment by yuyay** [comment]
Hi @krshrimali,

Sorry for the inconvenience.
The server that we place STAIR Actions is currently shut down due to maintenance until 7th April (JST).
Please retry to download after 8th April.

**Comment by krshrimali** [comment]
Hi @yuyay - Thank you for your response. Realy appreciate it, will check back after 8th April!
