### ISSUE TITLE
Missing zip files when downloading STAIR data set.

### ISSUE THREAD

**Issue by baptist** [STAIR-Lab-CIT/STAIR-actions#2]
Hi,

When trying to download the data set I noticed some action zip files are empty (eg., https://data.airc.aist.go.jp/stair-actions-v1.0/train/pointing_with_finger.zip). Should I change a URL in the downloading script? 

Thanks a lot in advance!

**Comment by yuyay** [comment]
Thank you for your comment.

> When trying to download the data set I noticed some action zip files are empty (eg., https://data.airc.aist.go.jp/stair-actions-v1.0/train/pointing_with_finger.zip). Should I change a URL in the downloading script?

No problem. This behavior is correct.
Some zip files only includes an action directory with no mp4 files.
These indicate that there is no video with type (C) in their actions.

**Comment by man-ai** [comment]
Hi,

That url is broken for me too.
Could someone access to the url?

**Comment by yuyay** [comment]
Hi @man-ai,
Sorry for inconvenience.
The download server is currently under maintenance. 
The maintenance will be finished during Nov. 28 (JST).
Please wait for restart.

**Comment by taureanamir** [comment]
@yuyay The server is still not functioning. Could you please check.
