### ISSUE TITLE
Dataset URL not accessible

### ISSUE THREAD

**Issue by taureanamir** [STAIR-Lab-CIT/STAIR-actions#4]
The url https://data.airc.aist.go.jp/stair-actions-v1.1/train/standing_up.zip is not accessible.

**Comment by yuyay** [comment]
Hi, @taureanamir

Now I can download it.
Could you try it again?

Thank you.

**Comment by taureanamir** [comment]
@yuyay, 

Great, it works now. Thanks for such a quick response.

Best,
Amir.
