### ISSUE TITLE
Donwload.sh fail

### ISSUE THREAD

**Issue by Co2Link** [STAIR-Lab-CIT/STAIR-actions#7]
I am trying to download this dataset on 2019.12.14 by running 'bash download.sh' but it shows

```
--2019-12-14 15:33:04--  (try: 3)  https://data.airc.aist.go.jp/stair-actions-v1.1/train/drinking.zip
Connecting to data.airc.aist.go.jp (data.airc.aist.go.jp)|163.220.33.57|:443... failed: Connection timed out.
Retrying.
```

How can i solve this?

**Comment by yuyay** [comment]
Hi @ling9601,

Sorry for inconvenience.
The download server is currently stopped because of maintenance.
It will be restarted at 10 a.m. on Dec. 16 (JST).

**Comment by yuyay** [comment]
**Updated:**
The maintenance will be ended at 10 a.m. on Dec. 20 (JST). Sorry for inconvenience.

**Comment by Co2Link** [comment]
> **Updated:**
> The maintenance will be ended at 10 a.m. on Dec. 20 (JST). Sorry for inconvenience.

Thank for your reply, i will close the issue once i finish downloading dataset.
